// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdl6Yih17mRJJqIbnvTQjY_e05sQB6m0s',
    appId: '1:1074624114220:web:4e2e49731d22f7e5766b89',
    messagingSenderId: '1074624114220',
    projectId: 'codenameapp123',
    authDomain: 'codenameapp123.firebaseapp.com',
    storageBucket: 'codenameapp123.firebasestorage.app',
    measurementId: 'G-2HQ4J44W24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEpkoy0ANaxHrRx60iQ7Ds8g9r6KMIZY',
    appId: '1:1074624114220:android:47bf5df93fbdb543766b89',
    messagingSenderId: '1074624114220',
    projectId: 'codenameapp123',
    storageBucket: 'codenameapp123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA636lekv8E0I6ac4Vp5NvPpw8gvPLKpOA',
    appId: '1:1074624114220:ios:6025ef2528699cea766b89',
    messagingSenderId: '1074624114220',
    projectId: 'codenameapp123',
    storageBucket: 'codenameapp123.firebasestorage.app',
    iosBundleId: 'com.example.codenameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA636lekv8E0I6ac4Vp5NvPpw8gvPLKpOA',
    appId: '1:1074624114220:ios:6025ef2528699cea766b89',
    messagingSenderId: '1074624114220',
    projectId: 'codenameapp123',
    storageBucket: 'codenameapp123.firebasestorage.app',
    iosBundleId: 'com.example.codenameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdl6Yih17mRJJqIbnvTQjY_e05sQB6m0s',
    appId: '1:1074624114220:web:9f1d4ff8e5a04d13766b89',
    messagingSenderId: '1074624114220',
    projectId: 'codenameapp123',
    authDomain: 'codenameapp123.firebaseapp.com',
    storageBucket: 'codenameapp123.firebasestorage.app',
    measurementId: 'G-016PQR6KBB',
  );
}
